USE master
CREATE DATABASE PRUTL_APP;
GO
CREATE LOGIN [PRUTL\APP_SQL01_PRUTL_APP_Datawriter] FROM WINDOWS;
GRANT CONNECT TO [PRUTL\APP_SQL01_PRUTL_APP_Datawriter];

USE PRUTL_APP
CREATE USER [PRUTL\APP_SQL01_PRUTL_APP_Datawriter] FOR LOGIN [PRUTL\APP_SQL01_PRUTL_APP_Datawriter]
ALTER ROLE db_datawriter ADD MEMBER [PRUTL\APP_SQL01_PRUTL_APP_Datawriter]


--USE PRUTL_APP
--DROP USER [PRUTL\APP_SQL01_PRUTL_APP_Datawriter]

--USE master
--DROP LOGIN [PRUTL\APP_SQL01_PRUTL_APP_Datawriter]
--REVOKE CONNECT TO [PRUTL\APP_SQL01_PRUTL_APP_Datawriter]

--DROP DATABASE PRUTL_APP